version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - APP_ENV=development
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=9000
      - DATABASE_URL=postgresql://postgres:seagate@localhost:5432/gpp_fastapi
      - JWT_SECRET=docker-development-secret-key
      - CORS_ORIGINS=http://localhost:3000
    command: python run.py --host 0.0.0.0 --port 9000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gpp_fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data: